// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/BusinessCase.tsx": () => import("../components/mockups/BusinessCase.tsx"),
  "./components/mockups/TraceExplorer.tsx": () => import("../components/mockups/TraceExplorer.tsx")
};
